namespace: k8ssandra-operator
resources:
- github.com/k8ssandra/k8ssandra-operator/config/deployments/control-plane?ref=${K8SSANDRA_VER}
images:
- name: k8ssandra/k8ssandra-operator
  newTag: ${K8SSANDRA_VER}
  newName: ${PULL_REGISTRY}/k8ssandra-operator/k8ssandra-operator
- name: k8ssandra/cass-operator
  newTag: ${CASS_OPER_VER}
  newName: ${PULL_REGISTRY}/k8ssandra-operator/cass-operator
