kind: ConfigMap
apiVersion: v1
metadata:
  name: cass-operator-manager-config
data:
  image_config.yaml: |
    apiVersion: config.k8ssandra.io/v1beta1
    kind: ImageConfig
    metadata:
      name: image-config
    images:
      system-logger: "k8ssandra/system-logger:${CASS_OPER_VER}"
      config-builder: "k8ssandra/cass-config-builder:${CASS_CONFIG_BUILDER_VER}"
      cassandra:
        "${CASS_VER}": "k8ssandra/cass-management-api:${CASS_VER}"
    imageRegistry: "${PROXY_REGISTRY}"
    imagePullPolicy: IfNotPresent
    defaults:
      cassandra:
        repository: "k8ssandra/cass-management-api"
