resources:
- ${K8SSANDRA_WORKDIR}/tmp/cert-manager.yaml
images:
- name: quay.io/jetstack/cert-manager-cainjector
  newTag: ${CERT_MGR_VER}
  newName: ${PULL_REGISTRY}/cert-manager/cert-manager-cainjector
- name: quay.io/jetstack/cert-manager-controller
  newTag: ${CERT_MGR_VER}
  newName: ${PULL_REGISTRY}/cert-manager/cert-manager-controller
- name: quay.io/jetstack/cert-manager-webhook
  newTag: ${CERT_MGR_VER}
  newName: ${PULL_REGISTRY}/cert-manager/cert-manager-webhook
