apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: k8ssandra-cluster
spec:
  cassandra:
    serverVersion: ${CASS_VER}
    serverImage: ${PULL_REGISTRY}/k8ssandra-operator/cass-management-api:${CASS_VER}
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: k8ssandra-sc
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        selector:
          matchLabels:
            app: k8ssandra-cluster
    config:
      jvmOptions:
        heapSize: 1024M
    networking:
      hostNetwork: false 
    datacenters:
      - metadata:
          name: dc1
        size: 1
        jmxInitContainerImage:
          registry: ${PULL_REGISTRY}
          repository: k8ssandra-operator
          name: busybox
          tag: ${BUSYBOX_VER}
        stargate:
          size: 1
          heapSize: 512M
          allowStargateOnDataNodes: true
          containerImage: 
            registry: ${PULL_REGISTRY}
            repository: k8ssandra-operator
            name: stargate-4_0
            tag: ${STARGATE_VER}
