apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${ca_cert}
    server: ${cluster_addr}
  name: ${cluster}
contexts:
- context:
    cluster: ${cluster}
    user: ${cluster}-k8ssandra-operator
  name: ${cluster}
current-context: ${cluster}
kind: Config
preferences: {}
users:
- name: ${cluster}-k8ssandra-operator
  user:
    token: ${sa_token}
