apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: k8ssandra-cluster
  name: k8ssandra-cluster-0
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 20Gi
  hostPath:
    path: /mnt/pv-data/k8ssandrapv
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k8ssandra-sc
  claimRef:
    name: server-data-k8ssandra-cluster-dc1-default-sts-0
    namespace: k8ssandra-operator
